/-
Copyright (c) 2026 The Erdős #1220 formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Erdős Problem #1220 — comparator challenge (trusted statements)

GENERATED by `sync_challenge.py` from `Challenge.template`; do not edit by hand.

This file is the *trusted* half of a comparator challenge
(https://github.com/leanprover/comparator), modelled on elliotglazer/erdos501's `Challenge.lean`:
it states, with `sorry`, exactly what `Solution.lean` proves.  It imports **Mathlib only**.  The
language `L` of set theory, the formula combinators, the theory `ZFC` and the standard structure
`zfsetStructure` on `ZFSet` are copied *verbatim* (Part A0) from erdos501's statement module
`Erdos501.FOL.Statement` (elliotglazer/erdos501 at 218d1c1, Apache-2.0), keeping exactly the
declarations used by the #1220 targets, so that they are literally the constants of erdos501's
comparator challenge and of the library used by `Solution.lean`.

## The problem (erdosproblems.com/1220; Erdős–Hajnal 1971)

Let `λ` be a singular cardinal such that `λ` and `cf λ` are `ℵ₀`-inaccessible (`μ ^ ℵ₀ < κ` for
every cardinal `μ < κ`).  Is it true that `λ → (λ, ℵ₁)²`?

## The two targets

1. `erdos1220_not_provable` — `ZFC` does not entail `Erdos1220`, the first-order rendering of the
   positive answer: some model of `ZFC` satisfies its negation.  The witness is the singular
   strong-limit cardinal `λ = ℶ_{𝔠⁺}` of the ground model (cofinality `𝔠⁺`; `λ` and `cf λ` are
   `ℵ₀`-inaccessible), made to violate `λ → (λ, ℵ₁)²` by the Shelah–Stanley forcing of Sh:258 §3
   (APAL 36 (1987)) — block-preserving histories of basic conditions — whose Boolean-valued model
   is turned into a two-valued model by Flypitch's completeness theorem.
2. `erdos1220_sentence_faithful` — in Mathlib's `ZFSet` the sentence `Erdos1220` holds iff the
   Mathlib-level statement `Erdos1220.Problem1220.{0}` holds.

Independence is stated semantically exactly as in erdos501 (`⊨ᵇ` over Mathlib `ModelType`s of
`ZFC` with carrier in `Type 0`; by Löwenheim–Skolem no restriction).  Only the negative direction
(non-provability) is claimed; the positive direction (`¬ (ZFC ⊨ᵇ ∼Erdos1220)`) is *not* a target.

## Reading guide — what a referee has to check by hand

* Part A0: the language `L`, `ZFC`, the combinators and `zfsetStructure` (verbatim from erdos501);
* Part A1/A2 below: the Mathlib-level statement (`IsOmegaInaccessible`, `PairArrow`, `Hypotheses`,
  `Problem1220`) and the sentence `Erdos1220` with its helper formulas.  Target 2 reduces the audit
  of the sentence to the audit of `Problem1220`.
-/
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.SetTheory.Cardinal.Continuum
import Mathlib.SetTheory.Cardinal.Aleph
import Mathlib.SetTheory.Cardinal.Regular
import Mathlib.Data.Set.Card
import Mathlib.Data.Finset.Card
import Mathlib.ModelTheory.Satisfiability
import Mathlib.SetTheory.ZFC.Basic

/-! ## Part A0 — the language, `ZFC` and `zfsetStructure` (verbatim from erdos501) -/

section Language

open MeasureTheory
open scoped Cardinal FirstOrder
open FirstOrder FirstOrder.Language

namespace Erdos501.FOL

/-! ### The language `L` of set theory -/

/-- Function symbols: `∅` (arity 0), `ω` (arity 0), `𝒫` (arity 1), `⋃` (arity 1),
the ordered pair `(·,·)` (arity 2). -/
inductive Func : ℕ → Type
  | emptyset : Func 0
  | omega : Func 0
  | powerset : Func 1
  | union : Func 1
  | pair : Func 2

/-- Relation symbols: `∈` (arity 2). -/
inductive Rel : ℕ → Type
  | mem : Rel 2

/-- The first-order language of set theory used here: `∅, ω, 𝒫, ⋃, (·,·)` and `∈`. -/
abbrev L : Language := ⟨Func, Rel⟩

/-! ### Depth-polymorphic formulas

Formulas of Mathlib's `ModelTheory` are `L.BoundedFormula Empty n` with `n` bound
variables `&0, …, &(n-1)`; a quantifier `∀'`/`∃'` binds the *last* variable
`&n`.  So `&ℓ` is the variable of de Bruijn *level* `ℓ` (`0` = outermost).  We
build formulas through *depth-polymorphic* formulas `Fm := ∀ n, L.BoundedFormula Empty n`
and terms `Tm := ∀ n, L.Term (Empty ⊕ Fin n)`: `allF fun x => φ x` binds a new
variable and passes its level `x` to the body, so that scoping is checked by
Lean and no lifting is ever needed; a sentence is obtained by evaluating at
depth `0` (`toSentence`). -/

/-- Depth-polymorphic formulas. -/
abbrev Fm : Type := ∀ n : ℕ, L.BoundedFormula Empty n

/-- Depth-polymorphic terms. -/
abbrev Tm : Type := ∀ n : ℕ, L.Term (Empty ⊕ Fin n)

/-- The variable of de Bruijn level `ℓ` (`0` = outermost).  (For `ℓ ≥ n` — never
used — it is the constant `∅`.) -/
def varT (ℓ : ℕ) : Tm := fun n =>
  if h : ℓ < n then Term.var (Sum.inr ⟨ℓ, h⟩) else Term.func Func.emptyset Fin.elim0

/-- The constant `∅`. -/
def empT : Tm := fun _ => Term.func Func.emptyset Fin.elim0

/-- The constant `ω`. -/
def omT : Tm := fun _ => Term.func Func.omega Fin.elim0

/-- The power set `𝒫 t`. -/
def powT (t : Tm) : Tm := fun n => Term.func Func.powerset ![t n]

/-- The union `⋃ t`. -/
def unionT (t : Tm) : Tm := fun n => Term.func Func.union ![t n]

/-- The ordered pair `(s, t)`. -/
def pairT (s t : Tm) : Tm := fun n => Term.func Func.pair ![s n, t n]

/-- `s ∈ t`. -/
def memF (s t : Tm) : Fm := fun n => Relations.boundedFormula₂ (Rel.mem : L.Relations 2) (s n) (t n)

/-- `s = t`. -/
def eqF (s t : Tm) : Fm := fun n => Term.bdEqual (s n) (t n)

def andF (φ ψ : Fm) : Fm := fun n => φ n ⊓ ψ n
def orF (φ ψ : Fm) : Fm := fun n => φ n ⊔ ψ n
def impF (φ ψ : Fm) : Fm := fun n => (φ n).imp (ψ n)
def iffF (φ ψ : Fm) : Fm := fun n => (φ n).iff (ψ n)
def notF (φ : Fm) : Fm := fun n => (φ n).not

/-- `∀ x, φ x`; the body receives the *level* of the bound variable. -/
def allF (φ : ℕ → Fm) : Fm := fun n => (φ n (n + 1)).all

/-- `∃ x, φ x`; the body receives the *level* of the bound variable. -/
def exF (φ : ℕ → Fm) : Fm := fun n => (φ n (n + 1)).ex

/-- `∀ x ∈ t, φ x`. -/
def allIn (t : Tm) (φ : ℕ → Fm) : Fm := allF fun x => impF (memF (varT x) t) (φ x)

/-- `∃ x ∈ t, φ x`. -/
def exIn (t : Tm) (φ : ℕ → Fm) : Fm := exF fun x => andF (memF (varT x) t) (φ x)

/-- Conjunction of a list of formulas (`⊤` for the empty list). -/
def andsF : List Fm → Fm
  | [] => notF (fun _ => ⊥)
  | [φ] => φ
  | φ :: φs => andF φ (andsF φs)

/-- The sentence denoted by a depth-polymorphic formula (evaluation at depth `0`). -/
def toSentence (φ : Fm) : L.Sentence := φ 0

/-- `s ⊆ t`. -/
def subsetF (s t : Tm) : Fm := allF fun z => impF (memF (varT z) s) (memF (varT z) t)

/-! ### The theory `ZFC` -/

/-- `∀ x, x ∉ ∅`. -/
def axiomOfEmptyset : L.Sentence := toSentence <|
  allF fun x => notF (memF (varT x) empT)

/-- `∀ x y z w, (x, y) = (z, w) ↔ x = z ∧ y = w`: the pairing symbol produces
ordered pairs. -/
def axiomOfOrderedPairs : L.Sentence := toSentence <|
  allF fun x => allF fun y => allF fun z => allF fun w =>
    iffF (eqF (pairT (varT x) (varT y)) (pairT (varT z) (varT w)))
      (andF (eqF (varT x) (varT z)) (eqF (varT y) (varT w)))

/-- `∀ x y, (∀ z, z ∈ x ↔ z ∈ y) → x = y`. -/
def axiomOfExtensionality : L.Sentence := toSentence <|
  allF fun x => allF fun y =>
    impF (allF fun z => iffF (memF (varT z) (varT x)) (memF (varT z) (varT y)))
      (eqF (varT x) (varT y))

/-- `∀ u x, x ∈ ⋃ u ↔ ∃ y, y ∈ u ∧ x ∈ y`. -/
def axiomOfUnion : L.Sentence := toSentence <|
  allF fun u => allF fun x =>
    iffF (memF (varT x) (unionT (varT u)))
      (exF fun y => andF (memF (varT y) (varT u)) (memF (varT x) (varT y)))

/-- `∀ z y, y ∈ 𝒫 z ↔ ∀ x, x ∈ y → x ∈ z`. -/
def axiomOfPowerset : L.Sentence := toSentence <|
  allF fun z => allF fun y =>
    iffF (memF (varT y) (powT (varT z)))
      (allF fun x => impF (memF (varT x) (varT y)) (memF (varT x) (varT z)))

/-- `a` (a variable level) is an ordinal: `∈` is trichotomous and well-founded on
`a`, and `a` is transitive. -/
def ordF (a : ℕ) : Fm :=
  andF
    (andF
      -- ∈-trichotomy on `a`
      (allF fun y => impF (memF (varT y) (varT a)) (allF fun z => impF (memF (varT z) (varT a))
        (orF (orF (eqF (varT y) (varT z)) (memF (varT y) (varT z))) (memF (varT z) (varT y)))))
      -- ∈-well-foundedness on `a`: every nonempty subset has an ∈-minimal element
      (allF fun y => impF (subsetF (varT y) (varT a)) (impF (notF (eqF (varT y) empT))
        (exF fun z => andF (memF (varT z) (varT y))
          (allF fun w => impF (memF (varT w) (varT y)) (notF (memF (varT w) (varT z))))))))
    -- transitivity of `a`
    (allF fun y => impF (memF (varT y) (varT a)) (subsetF (varT y) (varT a)))

/-- Infinity: `∅ ∈ ω`, `ω` is closed under "there is a larger element", `ω` is an
ordinal, and `ω` is contained in every ordinal `a` with `∅ ∈ a` closed under
"there is a larger element" — i.e. `ω` is the least infinite ordinal. -/
def axiomOfInfinity : L.Sentence := toSentence <|
  andF
    (andF
      (andF
        (memF empT omT)
        (allF fun x => impF (memF (varT x) omT)
          (exF fun y => andF (memF (varT y) omT) (memF (varT x) (varT y)))))
      (exF fun a => andF (ordF a) (eqF omT (varT a))))
    (allF fun a => impF (ordF a) (impF
      (andF (memF empT (varT a))
        (allF fun x => impF (memF (varT x) (varT a))
          (exF fun y => andF (memF (varT y) (varT a)) (memF (varT x) (varT y)))))
      (subsetF omT (varT a))))

/-- `∀ x, x ≠ ∅ → ∃ y ∈ x, ∀ z ∈ x, z ∉ y`. -/
def axiomOfRegularity : L.Sentence := toSentence <|
  allF fun x => impF (notF (eqF (varT x) empT))
    (exF fun y => andF (memF (varT y) (varT x))
      (allF fun z => impF (memF (varT z) (varT x)) (notF (memF (varT z) (varT y)))))

/-- Zorn's lemma: if `x ≠ ∅` and the union of every chain `y ⊆ x` (a subset of `x`
linearly ordered by `⊆`) belongs to `x`, then `x` has a `⊆`-maximal element. -/
def zornsLemma : L.Sentence := toSentence <|
  allF fun x => impF (notF (eqF (varT x) empT)) (impF
    (allF fun y => impF
      (andF (subsetF (varT y) (varT x))
        (allF fun w₁ => allF fun w₂ =>
          impF (andF (memF (varT w₁) (varT y)) (memF (varT w₂) (varT y)))
            (orF (subsetF (varT w₁) (varT w₂)) (subsetF (varT w₂) (varT w₁)))))
      (memF (unionT (varT y)) (varT x)))
    (exF fun m => andF (memF (varT m) (varT x))
      (allF fun z => impF (memF (varT z) (varT x))
        (impF (subsetF (varT m) (varT z)) (eqF (varT m) (varT z))))))

/-- Strong collection for the formula `ψ`, whose bound variables are the `n`
parameters `&0, …, &(n-1)`, `x = &n` and `y = &(n+1)`:

`∀ params, ∀ u, (∀ x ∈ u, ∃ y, ψ) → ∃ v, (∀ x ∈ u, ∃ y ∈ v, ψ) ∧ (∀ y ∈ v, ∃ x ∈ u, ψ)`.

`ψ.liftAt k n` is `ψ` with `k` new variables inserted at level `n` (i.e. below
`x` and `y`, above the parameters); in the last conjunct the roles of the two
innermost variables are exchanged by introducing a copy `y'` of `y`.  The
levels of the variables in the three clauses are (`p` = parameters):
`p, u, x, y`; `p, u, v, x, y`; `p, u, v, y, x, y'`. -/
def collectionAxiom (n : ℕ) (ψ : L.BoundedFormula Empty (n + 2)) : L.Sentence :=
  BoundedFormula.alls (n := n + 1) <|
    BoundedFormula.imp
      -- ∀ x ∈ u, ∃ y, ψ                                    (levels: p, u, x, y)
      (BoundedFormula.all (BoundedFormula.imp (Relations.boundedFormula₂ (Rel.mem : L.Relations 2) (Term.var (Sum.inr ⟨n + 1, by omega⟩)) (Term.var (Sum.inr ⟨n, by omega⟩))) (BoundedFormula.ex (ψ.liftAt 1 n))))
      (BoundedFormula.ex
        -- ∀ x ∈ u, ∃ y ∈ v, ψ                              (levels: p, u, v, x, y)
        ((BoundedFormula.all (BoundedFormula.imp (Relations.boundedFormula₂ (Rel.mem : L.Relations 2) (Term.var (Sum.inr ⟨n + 2, by omega⟩)) (Term.var (Sum.inr ⟨n, by omega⟩))) (BoundedFormula.ex ((Relations.boundedFormula₂ (Rel.mem : L.Relations 2) (Term.var (Sum.inr ⟨n + 3, by omega⟩)) (Term.var (Sum.inr ⟨n + 1, by omega⟩))) ⊓ (ψ.liftAt 2 n))))) ⊓
         -- ∀ y ∈ v, ∃ x ∈ u, ∃ y', y' = y ∧ ψ              (levels: p, u, v, y, x, y')
         (BoundedFormula.all (BoundedFormula.imp (Relations.boundedFormula₂ (Rel.mem : L.Relations 2) (Term.var (Sum.inr ⟨n + 2, by omega⟩)) (Term.var (Sum.inr ⟨n + 1, by omega⟩))) (BoundedFormula.ex ((Relations.boundedFormula₂ (Rel.mem : L.Relations 2) (Term.var (Sum.inr ⟨n + 3, by omega⟩)) (Term.var (Sum.inr ⟨n, by omega⟩))) ⊓ (BoundedFormula.ex ((Term.bdEqual (Term.var (Sum.inr ⟨n + 4, by omega⟩)) (Term.var (Sum.inr ⟨n + 2, by omega⟩))) ⊓ (ψ.liftAt 3 n)))))))))

/-- **The theory `ZFC`**: extensionality, empty set, ordered pairs, union, power
set, infinity, regularity, Zorn's lemma, and the strong collection scheme.  This
is the axiom system of Han–van Doorn's Flypitch formalization of ZFC; it is
equivalent to the usual ZFC. -/
def ZFC : L.Theory :=
  {axiomOfEmptyset, axiomOfOrderedPairs, axiomOfExtensionality, axiomOfUnion,
    axiomOfPowerset, axiomOfInfinity, axiomOfRegularity, zornsLemma} ∪
  ⋃ n : ℕ, Set.range (collectionAxiom n)

/-- `f(x) = y`, for a function `f` given as a set of ordered pairs. -/
def appF (f x y : Tm) : Fm := memF (pairT x y) f

/-- `f` is a (total, single-valued) function from `dom` to `cod`: every `x ∈ dom`
has exactly one `f`-value, and it lies in `cod`. -/
def isFunF (dom cod f : Tm) : Fm :=
  allIn dom fun x => exIn cod fun y =>
    andF (appF f (varT x) (varT y))
      (allF fun y' => impF (appF f (varT x) (varT y')) (eqF (varT y') (varT y)))

/-! ### The standard interpretation in Mathlib's `ZFSet` -/

/-- Mathlib's `ZFSet` as an `L`-structure: `∅ ↦ ∅`, `ω ↦ ω`, `𝒫 ↦ powerset`,
`⋃ ↦ sUnion`, `(·,·) ↦ Kuratowski pair`, `∈ ↦ ∈`. -/
noncomputable instance zfsetStructure : L.Structure ZFSet.{0} where
  funMap {n} f xs :=
    match n, f, xs with
    | _, Func.emptyset, _ => ∅
    | _, Func.omega, _ => ZFSet.omega
    | _, Func.powerset, xs => ZFSet.powerset (xs 0)
    | _, Func.union, xs => ZFSet.sUnion (xs 0)
    | _, Func.pair, xs => ZFSet.pair (xs 0) (xs 1)
  RelMap {n} r xs :=
    match n, r, xs with
    | _, Rel.mem, xs => xs 0 ∈ xs 1

end Erdos501.FOL

end Language

/-! ## Part A1/A2 — definitions (verbatim copies of the library's statement modules) -/

section Problem

open Cardinal Order

universe u

namespace Erdos1220

/-- Closure below `κ` under taking countable cardinal powers. -/
def IsOmegaInaccessible (κ : Cardinal.{u}) : Prop :=
  ∀ μ : Cardinal.{u}, μ < κ → μ ^ ℵ₀ < κ

/-- The asymmetric binary partition arrow `κ → (α, β)²`.

The coloring is defined on unordered two-element subsets. The two alternatives
have the indicated exact cardinalities, and every pair inside the witness has
the specified color. This is the binary specialization of the formulation used
in FormalConjecturesForMathlib's `cardinalPartitionRel`.
-/
def PairArrow (κ α β : Cardinal.{u}) : Prop :=
  ∀ (V : Type u), #V = κ →
    ∀ color : {e : Finset V // e.card = 2} → Bool,
      (∃ H : Set V, #H = α ∧
        ∀ (e : Finset V) (he : e.card = 2),
          (↑e : Set V) ⊆ H → color ⟨e, he⟩ = false) ∨
      (∃ H : Set V, #H = β ∧
        ∀ (e : Finset V) (he : e.card = 2),
          (↑e : Set V) ⊆ H → color ⟨e, he⟩ = true)

/-- All hypotheses in the website's formulation. -/
def Hypotheses (κ : Cardinal.{u}) : Prop :=
  κ.IsSingular ∧ IsOmegaInaccessible κ ∧ IsOmegaInaccessible κ.ord.cof

/-- The universal positive assertion, in one fixed universe. -/
def Problem1220 : Prop :=
  ∀ κ : Cardinal.{u}, Hypotheses κ → PairArrow κ κ ℵ₁

end Erdos1220

end Problem

section Sentence

open scoped Cardinal FirstOrder
open FirstOrder FirstOrder.Language
open Erdos501.FOL

namespace Erdos1220.FOL

/-- `|A| ≤ |B|`: some `f` is an injective function from `A` to `B`. -/
def leqF (A B : Tm) : Fm :=
  exF fun f => andF (isFunF A B (varT f))
    (allIn A fun x => allIn A fun x' => allF fun y =>
      impF (appF (varT f) (varT x) (varT y)) <| impF (appF (varT f) (varT x') (varT y)) <|
        eqF (varT x) (varT x'))

/-- `|A| = |B|`. -/
def eqCardF (A B : Tm) : Fm := andF (leqF A B) (leqF B A)

/-- `k` (a level) is a cardinal, i.e. an initial ordinal. -/
def cardinalF (k : ℕ) : Fm :=
  andF (ordF k) (allIn (varT k) fun a => notF (leqF (varT k) (varT a)))

/-- `S` is cofinal in the ordinal `l`: `∀ β ∈ l, ∃ γ ∈ S, β ∈ γ ∨ β = γ`. -/
def cofinalF (S l : Tm) : Fm :=
  allIn l fun b => exIn S fun g => orF (memF (varT b) (varT g)) (eqF (varT b) (varT g))

/-- The cardinal `l` is singular: `ℵ₀ ≤ |l|` and some cofinal `S ⊆ l` has `|S| < |l|`. -/
def singularF (l : ℕ) : Fm :=
  andF (leqF omT (varT l))
    (exF fun S => andsF [subsetF (varT S) (varT l), cofinalF (varT S) (varT l),
      notF (leqF (varT l) (varT S))])

/-- `d = cf(l)`: `d` is a cardinal, some cofinal `S ⊆ l` has `|S| = |d|`, and every cofinal
`S ⊆ l` has `|d| ≤ |S|`. -/
def cofF (l d : ℕ) : Fm :=
  andsF [cardinalF d,
    exF (fun S => andsF [subsetF (varT S) (varT l), cofinalF (varT S) (varT l),
      eqCardF (varT S) (varT d)]),
    allF (fun S => impF (subsetF (varT S) (varT l)) <| impF (cofinalF (varT S) (varT l)) <|
      leqF (varT d) (varT S))]

/-- `f` is a function from `D` to `C` in the strict sense: a set of ordered pairs `(x, y)` with
`x ∈ D`, `y ∈ C`, relating each `x ∈ D` to exactly one `y` (Mathlib's `ZFSet.IsFunc`). -/
def fnF (D C f : Tm) : Fm :=
  andF (allIn f fun z => exIn D fun x => exIn C fun y => eqF (varT z) (pairT (varT x) (varT y)))
    (allIn D fun x => exF fun y => andF (appF f (varT x) (varT y))
      (allF fun y' => impF (appF f (varT x) (varT y')) (eqF (varT y') (varT y))))

/-- `|μ| ^ ℵ₀ < |k|` for a cardinal `k`: for some `α ∈ k` there is a set `h` relating every
function `f : ω → μ` to some `β ∈ α`, with no two distinct functions related to the same `β`
(i.e. the set of functions `ω → μ` injects into `α`). -/
def powLtF (μ k : Tm) : Fm :=
  exIn k fun α => exF fun h => andF
    (allF fun f => impF (fnF omT μ (varT f)) (exIn (varT α) fun b => appF (varT h) (varT f) (varT b)))
    (allF fun f => allF fun f' => allF fun b =>
      impF (fnF omT μ (varT f)) <| impF (fnF omT μ (varT f')) <|
      impF (appF (varT h) (varT f) (varT b)) <| impF (appF (varT h) (varT f') (varT b)) <|
        eqF (varT f) (varT f'))

/-- The cardinal `k` is `ℵ₀`-inaccessible: `μ ^ ℵ₀ < k` for every cardinal `μ < k`. -/
def omegaInaccF (k : ℕ) : Fm :=
  allIn (varT k) fun μ => impF (cardinalF μ) (powLtF (varT μ) (varT k))

/-- `i = 0`, i.e. `i = ∅`. -/
def zeroF (i : Tm) : Fm := eqF i empT

/-- `i = 1`, i.e. `i = {∅}`. -/
def oneF (i : Tm) : Fm := allF fun z => iffF (memF (varT z) i) (eqF (varT z) empT)

/-- `c` is a colouring `[l]² → {0, 1}`: every `(α, β)` with `α ∈ β ∈ l` has exactly one
`c`-value, and it is `0` or `1`. -/
def colouringF (l c : Tm) : Fm :=
  allIn l fun a => allIn l fun b => impF (memF (varT a) (varT b)) <|
    exF fun i => andsF [appF c (pairT (varT a) (varT b)) (varT i),
      orF (zeroF (varT i)) (oneF (varT i)),
      allF fun i' => impF (appF c (pairT (varT a) (varT b)) (varT i')) (eqF (varT i') (varT i))]

/-- `H` is homogeneous for `c` in colour `0`. -/
def homog0F (c H : Tm) : Fm :=
  allIn H fun a => allIn H fun b => impF (memF (varT a) (varT b)) <|
    allF fun i => impF (appF c (pairT (varT a) (varT b)) (varT i)) (zeroF (varT i))

/-- `H` is homogeneous for `c` in colour `1`. -/
def homog1F (c H : Tm) : Fm :=
  allIn H fun a => allIn H fun b => impF (memF (varT a) (varT b)) <|
    allF fun i => impF (appF c (pairT (varT a) (varT b)) (varT i)) (oneF (varT i))

/-- `w = ω₁`: `w` is an ordinal, `¬ |w| ≤ |ω|`, and `|a| ≤ |ω|` for all `a ∈ w`. -/
def omega1F (w : ℕ) : Fm :=
  andsF [ordF w, notF (leqF (varT w) omT), allIn (varT w) fun a => leqF (varT a) omT]

set_option linter.dupNamespace false in
/-- **Erdős problem #1220 as a sentence of `L`**: for every singular cardinal `λ` such that `λ`
and `cf λ` are `ℵ₀`-inaccessible, every colouring `c : [λ]² → {0, 1}` has a set `H ⊆ λ` with
`|H| = |λ|` homogeneous in colour `0` or a set `H ⊆ λ` with `|H| = |ω₁|` homogeneous in colour `1`. -/
def Erdos1220 : L.Sentence :=
  toSentence <|
    allF fun l =>
      impF (andsF [cardinalF l, singularF l, omegaInaccF l,
          allF fun d => impF (cofF l d) (omegaInaccF d)]) <|
      allF fun c => impF (colouringF (varT l) (varT c)) <|
        orF
          (exF fun H => andsF [subsetF (varT H) (varT l), eqCardF (varT H) (varT l),
            homog0F (varT c) (varT H)])
          (exF fun w => andF (omega1F w) <|
            exF fun H => andsF [subsetF (varT H) (varT l), eqCardF (varT H) (varT w),
              homog1F (varT c) (varT H)])

end Erdos1220.FOL

end Sentence

/-! ## Part B — the statements -/

open scoped FirstOrder
open FirstOrder FirstOrder.Language
open Erdos501.FOL

/-- **A negative answer is consistent with ZFC**: `ZFC` does not entail `Erdos1220` — some model
of `ZFC` satisfies its negation (Shelah–Stanley 1987, §3). -/
theorem erdos1220_not_provable : ¬ (ZFC ⊨ᵇ Erdos1220.FOL.Erdos1220) := by
  sorry

/-- **Faithfulness of the rendering**: in Mathlib's `ZFSet` (erdos501's standard interpretation
of `∅, ω, 𝒫, ⋃, (·,·), ∈`), the sentence `Erdos1220` holds iff the Mathlib-level statement of the
problem holds. -/
theorem erdos1220_sentence_faithful :
    (ZFSet.{0} ⊨ Erdos1220.FOL.Erdos1220) ↔ Erdos1220.Problem1220.{0} := by
  sorry
