import Erdos1220.Flip
import Erdos1220.HistoryLimit
import Erdos1220.BlockPreservingClosure

/-!
# The weak order on block-preserving histories (Sh:258 §3.6, §3.8)

`FlipEquiv` is the equivalence relation generated by single flips.
`WeakExtends H K` ("`K` is stronger than `H`") means that `K` is
flip-equivalent to a pure extension of `H`.

We prove reflexivity, transitivity (by lifting finite flip words along pure
extensions using prefix naturality and `flip_flip`), that pure extension and
flip equivalence give weak extension, that flip equivalence preserves the
terminal condition (hence any coloring read off from it, and block coverage),
bounded closure for pure chains, countable closure of the weak order, and a
`μ⁺`-length strategic closure theorem: player II, answering every move of
player I by a flip-equivalent pure extension of its own previous position and
taking coherent unions at limits, can play at every stage below `(succ μ).ord`.
-/

open Cardinal Set Order

universe u

namespace Erdos1220

open BasicCondition History

/-- Block-preserving histories. -/
abbrev BPHistory (V I : Type u) (block : V → I) (μ : Cardinal.{u}) (hμ : ℵ₀ ≤ μ) :
    Type (u + 1) :=
  {H : History V I block μ hμ // H.BlockPreserving}

namespace BPHistory

variable {V I : Type u} {block : V → I} {μ : Cardinal.{u}} {hμ : ℵ₀ ≤ μ}

/-- The single flip at stage `i`. -/
noncomputable def flip (H : BPHistory V I block μ hμ) (i : Ordinal.{u})
    (hi : Order.succ i ≤ H.1.length) : BPHistory V I block μ hμ :=
  ⟨H.1.flip H.2 i hi, H.1.flip_blockPreserving H.2 i hi⟩

theorem flip_length (H : BPHistory V I block μ hμ) (i : Ordinal.{u})
    (hi : Order.succ i ≤ H.1.length) : (H.flip i hi).1.length = H.1.length := rfl

theorem flip_last (H : BPHistory V I block μ hμ) (i : Ordinal.{u})
    (hi : Order.succ i ≤ H.1.length) : (H.flip i hi).1.last = H.1.last :=
  History.flip_last _ _ _ _

theorem flip_flip (H : BPHistory V I block μ hμ) (i : Ordinal.{u})
    (hi : Order.succ i ≤ H.1.length) : (H.flip i hi).flip i hi = H :=
  Subtype.ext (H.1.flip_flip H.2 i hi)

/-- One flip step. -/
def FlipStep (H K : BPHistory V I block μ hμ) : Prop :=
  ∃ i, ∃ hi : Order.succ i ≤ H.1.length, K = H.flip i hi

theorem FlipStep.symm {H K : BPHistory V I block μ hμ} (h : FlipStep H K) :
    FlipStep K H := by
  obtain ⟨i, hi, rfl⟩ := h
  exact ⟨i, hi, (flip_flip H i hi).symm⟩

/-- Flip equivalence: the equivalence relation generated by single flips
(finite flip words). -/
def FlipEquiv : BPHistory V I block μ hμ → BPHistory V I block μ hμ → Prop :=
  Relation.EqvGen FlipStep

theorem FlipEquiv.refl (H : BPHistory V I block μ hμ) : FlipEquiv H H :=
  Relation.EqvGen.refl H

theorem FlipEquiv.symm {H K : BPHistory V I block μ hμ} (h : FlipEquiv H K) :
    FlipEquiv K H :=
  Relation.EqvGen.symm _ _ h

theorem FlipEquiv.trans {H K L : BPHistory V I block μ hμ} (h : FlipEquiv H K)
    (h' : FlipEquiv K L) : FlipEquiv H L :=
  Relation.EqvGen.trans _ _ _ h h'

theorem FlipEquiv.of_step {H K : BPHistory V I block μ hμ} (h : FlipStep H K) :
    FlipEquiv H K :=
  Relation.EqvGen.rel _ _ h

theorem FlipEquiv.flip (H : BPHistory V I block μ hμ) (i : Ordinal.{u})
    (hi : Order.succ i ≤ H.1.length) : FlipEquiv H (H.flip i hi) :=
  FlipEquiv.of_step ⟨i, hi, rfl⟩

/-- Flip equivalence does not change the terminal basic condition. -/
theorem FlipEquiv.last_eq {H K : BPHistory V I block μ hμ} (h : FlipEquiv H K) :
    H.1.last = K.1.last := by
  induction h with
  | rel x y hxy =>
    obtain ⟨i, hi, rfl⟩ := hxy
    exact (flip_last x i hi).symm
  | refl => rfl
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ ih1 ih2 => exact ih1.trans ih2

theorem FlipEquiv.length_eq {H K : BPHistory V I block μ hμ} (h : FlipEquiv H K) :
    H.1.length = K.1.length := by
  induction h with
  | rel x y hxy =>
    obtain ⟨i, hi, rfl⟩ := hxy
    rfl
  | refl => rfl
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ ih1 ih2 => exact ih1.trans ih2

/-- `WeakExtends H K`: `K` is stronger than `H`, i.e. `K` is flip-equivalent
to a pure extension of `H`. -/
def WeakExtends (H K : BPHistory V I block μ hμ) : Prop :=
  ∃ L : BPHistory V I block μ hμ, FlipEquiv K L ∧ PureExtends H.1 L.1

/-- A flip word from `K` to `L` can be lifted along any pure extension of `K`. -/
def Liftable (K L : BPHistory V I block μ hμ) : Prop :=
  ∀ M : BPHistory V I block μ hμ, PureExtends K.1 M.1 →
    ∃ M' : BPHistory V I block μ hμ, FlipEquiv M M' ∧ PureExtends L.1 M'.1

theorem Liftable.trans {K L N : BPHistory V I block μ hμ} (h : Liftable K L)
    (h' : Liftable L N) : Liftable K N := by
  intro M hM
  obtain ⟨M₁, hM₁, hL⟩ := h M hM
  obtain ⟨M₂, hM₂, hN⟩ := h' M₁ hL
  exact ⟨M₂, hM₁.trans hM₂, hN⟩

theorem liftable_of_step {K L : BPHistory V I block μ hμ} (h : FlipStep K L) :
    Liftable K L := by
  obtain ⟨i, hi, rfl⟩ := h
  intro M hKM
  exact ⟨M.flip i (hi.trans hKM.length_le), FlipEquiv.flip M i _,
    History.flip_pureExtends K.2 M.2 hKM i hi⟩

/-- Prefix naturality for whole flip words, in both directions. -/
theorem FlipEquiv.liftable {K L : BPHistory V I block μ hμ} (h : FlipEquiv K L) :
    Liftable K L ∧ Liftable L K := by
  induction h with
  | rel x y hxy => exact ⟨liftable_of_step hxy, liftable_of_step hxy.symm⟩
  | refl x =>
    exact ⟨fun M hM => ⟨M, FlipEquiv.refl M, hM⟩, fun M hM => ⟨M, FlipEquiv.refl M, hM⟩⟩
  | symm x y _ ih => exact ⟨ih.2, ih.1⟩
  | trans x y z _ _ ih1 ih2 => exact ⟨ih1.1.trans ih2.1, ih2.2.trans ih1.2⟩

theorem WeakExtends.refl (H : BPHistory V I block μ hμ) : WeakExtends H H :=
  ⟨H, FlipEquiv.refl H, pureExtends_refl H.1⟩

theorem WeakExtends.of_pure {H K : BPHistory V I block μ hμ} (h : PureExtends H.1 K.1) :
    WeakExtends H K :=
  ⟨K, FlipEquiv.refl K, h⟩

theorem WeakExtends.of_flipEquiv {H K : BPHistory V I block μ hμ} (h : FlipEquiv H K) :
    WeakExtends H K :=
  ⟨H, h.symm, pureExtends_refl H.1⟩

theorem WeakExtends.trans {H K N : BPHistory V I block μ hμ} (h : WeakExtends H K)
    (h' : WeakExtends K N) : WeakExtends H N := by
  obtain ⟨L, hKL, hHL⟩ := h
  obtain ⟨M, hNM, hKM⟩ := h'
  obtain ⟨M', hMM', hLM'⟩ := hKL.liftable.1 M hKM
  exact ⟨M', hNM.trans hMM', hHL.trans hLM'⟩

/-- Flip-equivalent histories are equivalent in the weak order. -/
theorem FlipEquiv.weak_both {H K : BPHistory V I block μ hμ} (h : FlipEquiv H K) :
    WeakExtends H K ∧ WeakExtends K H :=
  ⟨WeakExtends.of_flipEquiv h, WeakExtends.of_flipEquiv h.symm⟩

/-- The terminal coloring only grows along the weak order. -/
theorem WeakExtends.last_extends {H K : BPHistory V I block μ hμ} (h : WeakExtends H K) :
    Extends H.1.last K.1.last := by
  obtain ⟨L, hKL, hHL⟩ := h
  rw [hKL.last_eq]
  exact hHL.last_extends

/-- Every block is represented in the terminal support. -/
def CoversBlocks (p : BasicCondition V I block μ) : Prop :=
  ∀ b : I, ∃ x ∈ p.support, block x = b

theorem FlipEquiv.coversBlocks_iff {H K : BPHistory V I block μ hμ} (h : FlipEquiv H K) :
    CoversBlocks H.1.last ↔ CoversBlocks K.1.last := by
  rw [h.last_eq]

theorem WeakExtends.coversBlocks {H K : BPHistory V I block μ hμ} (h : WeakExtends H K)
    (hH : CoversBlocks H.1.last) : CoversBlocks K.1.last := by
  intro b
  obtain ⟨x, hx, hxb⟩ := hH b
  exact ⟨x, h.last_extends.1 hx, hxb⟩

theorem WeakExtends.of_flipEquiv_pure {H G U : BPHistory V I block μ hμ}
    (hHG : FlipEquiv H G) (hGU : PureExtends G.1 U.1) : WeakExtends H U :=
  (WeakExtends.of_flipEquiv hHG).trans (WeakExtends.of_pure hGU)

/-! ### Closure -/

/-- A pure chain of at most `μ` block-preserving histories has a
block-preserving pure upper bound; no length hypothesis is needed because
`succ μ` is regular. -/
theorem exists_pure_upper_bound {J : Type u} [LinearOrder J] [Nonempty J]
    (G : J → BPHistory V I block μ hμ) (hJ : #J ≤ μ)
    (hG : ∀ j k, j ≤ k → PureExtends (G j).1 (G k).1) :
    ∃ U : BPHistory V I block μ hμ, ∀ j, PureExtends (G j).1 U.1 := by
  have hlt : (⨆ j, (G j).1.length) < (Order.succ μ).ord := by
    apply Ordinal.iSup_lt_of_lt_cof
    · rw [(Cardinal.isRegular_succ hμ).cof_ord]
      exact hJ.trans_lt (Order.lt_succ μ)
    · exact fun j => (G j).1.length_lt
  let C : PureChain (V := V) (I := I) (block := block) (μ := μ) (hμ := hμ) J :=
    { history := fun j => (G j).1
      small := hJ
      increasing := hG
      length := ⨆ j, (G j).1.length
      length_lt := hlt
      length_le := fun j => Ordinal.le_iSup (fun j => (G j).1.length) j
      cofinal := fun _ hi => Ordinal.lt_iSup_iff.mp hi }
  exact ⟨⟨C.limit, C.limit_blockPreserving fun j => (G j).2⟩, C.pureExtends_limit⟩

section Countable

variable (H : ℕ → BPHistory V I block μ hμ) (hH : ∀ n, WeakExtends (H n) (H (n + 1)))

include hH in
theorem rep_step_exists (n : ℕ) (G : BPHistory V I block μ hμ) (hG : FlipEquiv (H n) G) :
    ∃ G' : BPHistory V I block μ hμ, FlipEquiv (H (n + 1)) G' ∧ PureExtends G.1 G'.1 := by
  obtain ⟨L, hL, hpure⟩ := hH n
  obtain ⟨M', hLM', hGM'⟩ := hG.liftable.1 L hpure
  exact ⟨M', hL.trans hLM', hGM'⟩

include hH in
/-- Pure-chain representatives of a weakly increasing `ω`-sequence. -/
noncomputable def reps : ∀ n : ℕ, {G : BPHistory V I block μ hμ // FlipEquiv (H n) G}
  | 0 => ⟨H 0, FlipEquiv.refl _⟩
  | n + 1 => ⟨Classical.choose (rep_step_exists H hH n (reps n).1 (reps n).2),
      (Classical.choose_spec (rep_step_exists H hH n (reps n).1 (reps n).2)).1⟩

theorem reps_succ (n : ℕ) : PureExtends (reps H hH n).1.1 (reps H hH (n + 1)).1.1 :=
  (Classical.choose_spec (rep_step_exists H hH n (reps H hH n).1 (reps H hH n).2)).2

theorem reps_mono {m n : ℕ} (hmn : m ≤ n) :
    PureExtends (reps H hH m).1.1 (reps H hH n).1.1 := by
  induction hmn with
  | refl => exact pureExtends_refl _
  | step _ ih => exact ih.trans (reps_succ H hH _)

include hH in
/-- Countable closure of the weak order. -/
theorem exists_weak_upper_bound_nat :
    ∃ U : BPHistory V I block μ hμ, ∀ n, WeakExtends (H n) U := by
  obtain ⟨U, hU⟩ := exists_pure_upper_bound (J := ULift.{u} ℕ)
    (fun n => (reps H hH n.down).1) (Cardinal.mk_le_aleph0.trans hμ)
    (fun j k hjk => reps_mono H hH (ULift.down_le.mpr hjk))
  exact ⟨U, fun n => WeakExtends.of_flipEquiv_pure (reps H hH n).2 (hU ⟨n⟩)⟩

end Countable

/-! ### Strategic closure for plays of length `μ⁺` -/

section Game

open scoped Classical in
/-- II's successor move: a pure extension of II's previous position `G`
which is flip-equivalent to I's move `K`. It depends only on `G` and `K`. -/
noncomputable def answerII (G K : BPHistory V I block μ hμ) : BPHistory V I block μ hμ :=
  if h : WeakExtends G K then Classical.choose h else G

theorem answerII_spec {G K : BPHistory V I block μ hμ} (h : WeakExtends G K) :
    FlipEquiv K (answerII G K) ∧ PureExtends G.1 (answerII G K).1 := by
  classical
  rw [answerII, dif_pos h]
  exact Classical.choose_spec h

open scoped Classical in
/-- II's limit move: a common pure extension of all earlier positions. It
depends only on the earlier positions. -/
noncomputable def limitII (start : BPHistory V I block μ hμ) (α : Ordinal.{u})
    (past : ∀ β, β < α → BPHistory V I block μ hμ) : BPHistory V I block μ hμ :=
  if h : ∃ U : BPHistory V I block μ hμ, ∀ β (hβ : β < α), PureExtends (past β hβ).1 U.1
  then Classical.choose h else start

theorem limitII_spec (start : BPHistory V I block μ hμ) (α : Ordinal.{u})
    (past : ∀ β, β < α → BPHistory V I block μ hμ)
    (h : ∃ U : BPHistory V I block μ hμ, ∀ β (hβ : β < α), PureExtends (past β hβ).1 U.1) :
    ∀ β (hβ : β < α), PureExtends (past β hβ).1 (limitII start α past).1 := by
  classical
  rw [limitII, dif_pos h]
  exact Classical.choose_spec h

variable (start : BPHistory V I block μ hμ)
  (moveI : ∀ α : Ordinal.{u}, (∀ γ, γ ≤ α → BPHistory V I block μ hμ) →
    BPHistory V I block μ hμ)

open scoped Classical in
/-- One stage of the play: `start` at `0`; at `β + 1` II answers I's move at
`β` (which may depend on all of II's positions up to `β`); at limits II plays
a coherent union. -/
noncomputable def playStep (α : Ordinal.{u}) (past : ∀ β, β < α → BPHistory V I block μ hμ) :
    BPHistory V I block μ hμ :=
  if α = 0 then start
  else if h : ∃ β, Order.succ β = α then
    answerII (past (Classical.choose h)
        (lt_of_lt_of_eq (Order.lt_succ _) (Classical.choose_spec h)))
      (moveI (Classical.choose h) fun γ hγ =>
        past γ (hγ.trans_lt (lt_of_lt_of_eq (Order.lt_succ _) (Classical.choose_spec h))))
  else limitII start α past

/-- II's positions along the play against I's strategy `moveI`. -/
noncomputable def play : Ordinal.{u} → BPHistory V I block μ hμ :=
  Ordinal.lt_wf.fix (playStep start moveI)

theorem play_eq (α : Ordinal.{u}) :
    play start moveI α = playStep start moveI α (fun β _ => play start moveI β) :=
  Ordinal.lt_wf.fix_eq _ α

theorem play_zero : play start moveI 0 = start := by
  rw [play_eq, playStep, if_pos rfl]

theorem play_succ (α : Ordinal.{u}) :
    play start moveI (Order.succ α) =
      answerII (play start moveI α) (moveI α fun γ _ => play start moveI γ) := by
  classical
  have h : ∃ β, Order.succ β = Order.succ α := ⟨α, rfl⟩
  rw [play_eq, playStep, if_neg (show Order.succ α ≠ 0 from fun h =>
    Order.succ_ne_bot α (h.trans Ordinal.bot_eq_zero.symm)), dif_pos h]
  have hc : Classical.choose h = α := Order.succ_injective (Classical.choose_spec h)
  rw [hc]

theorem play_limit (α : Ordinal.{u}) (h0 : α ≠ 0) (hlim : ¬ ∃ β, Order.succ β = α) :
    play start moveI α = limitII start α (fun β _ => play start moveI β) := by
  classical
  rw [play_eq, playStep, if_neg h0, dif_neg hlim]

variable (hmoveI : ∀ α past, WeakExtends (past α le_rfl) (moveI α past))

include hmoveI in
/-- II's answer at every successor stage is flip-equivalent to (hence weakly
equivalent to) I's move and purely extends II's previous position. -/
theorem play_succ_spec (α : Ordinal.{u}) :
    FlipEquiv (moveI α fun γ _ => play start moveI γ) (play start moveI (Order.succ α)) ∧
      PureExtends (play start moveI α).1 (play start moveI (Order.succ α)).1 := by
  rw [play_succ]
  exact answerII_spec (hmoveI α fun γ _ => play start moveI γ)

include hmoveI in
/-- **Strategic closure.** II's positions form a pure chain throughout every
stage below `(succ μ).ord`: at limit stages below `μ⁺` the coherent union
always exists. -/
theorem play_pure_chain (α : Ordinal.{u}) (hα : α < (Order.succ μ).ord) :
    ∀ β, β ≤ α → PureExtends (play start moveI β).1 (play start moveI α).1 := by
  induction α using WellFoundedLT.induction with
  | ind α ih =>
  rcases Ordinal.zero_or_succ_or_isSuccLimit α with h0 | ⟨γ, rfl⟩ | hlim
  · subst h0
    intro β hβ
    rw [le_antisymm hβ bot_le]
    exact pureExtends_refl _
  · have hγ : γ < Order.succ γ := Order.lt_succ γ
    have hstep := (play_succ_spec start moveI hmoveI γ).2
    intro β hβ
    rcases hβ.lt_or_eq with hlt | rfl
    · exact (ih γ hγ (hγ.trans hα) β (Order.lt_succ_iff.mp hlt)).trans hstep
    · exact pureExtends_refl _
  · have h0 : α ≠ 0 := hlim.ne_bot
    have hns : ¬ ∃ β, Order.succ β = α := by
      rintro ⟨β, rfl⟩
      exact hlim.succ_ne β rfl
    have hex : ∃ U : BPHistory V I block μ hμ,
        ∀ β (_ : β < α), PureExtends (play start moveI β).1 U.1 := by
      have : Nonempty α.ToType := Ordinal.nonempty_toType_iff.mpr h0
      have hcard : #α.ToType ≤ μ := by
        rw [Cardinal.mk_toType]
        exact Order.lt_succ_iff.mp (Cardinal.lt_ord.mp hα)
      obtain ⟨U, hU⟩ := exists_pure_upper_bound (J := α.ToType)
        (fun j => play start moveI (Ordinal.ToType.mk.symm j).1) hcard
        (fun j k hjk => ih _ (Ordinal.ToType.mk.symm k).2
          ((Ordinal.ToType.mk.symm k).2.trans hα) _
          (Ordinal.ToType.mk.symm.monotone hjk))
      refine ⟨U, fun β hβ => ?_⟩
      have := hU (Ordinal.ToType.mk ⟨β, hβ⟩)
      rwa [OrderIso.symm_apply_apply] at this
    have hspec := limitII_spec start α (fun β _ => play start moveI β) hex
    intro β hβ
    rcases hβ.lt_or_eq with hlt | rfl
    · rw [play_limit start moveI α h0 hns]
      exact hspec β hlt
    · exact pureExtends_refl _

include hmoveI in
/-- The whole play is descending in the weak order: I's move at stage `β`
is weakly below II's position at every later stage `α < μ⁺`. -/
theorem play_moveI_weak (β α : Ordinal.{u}) (hβα : β < α) (hα : α < (Order.succ μ).ord) :
    WeakExtends (moveI β fun γ _ => play start moveI γ) (play start moveI α) :=
  (WeakExtends.of_flipEquiv (play_succ_spec start moveI hmoveI β).1).trans
    (WeakExtends.of_pure (play_pure_chain start moveI hmoveI α hα _
      (Order.succ_le_of_lt hβα)))

include hmoveI in
/-- **II wins the closure game of length `μ⁺`.** For every strategy of
player I (each move a weak extension of II's current position, allowed to
depend on all of II's previous positions), II's canonical strategy produces
positions at every stage below `(succ μ).ord` such that II's positions form
a pure chain, every I-move is weakly below all later II-positions, and each
II-position weakly extends the preceding I-move. -/
theorem strategic_closure :
    play start moveI 0 = start ∧
    (∀ β α, β ≤ α → α < (Order.succ μ).ord →
      PureExtends (play start moveI β).1 (play start moveI α).1) ∧
    (∀ α, WeakExtends (play start moveI α) (moveI α fun γ _ => play start moveI γ) ∧
      WeakExtends (moveI α fun γ _ => play start moveI γ) (play start moveI (Order.succ α))) ∧
    (∀ β α, β < α → α < (Order.succ μ).ord →
      WeakExtends (moveI β fun γ _ => play start moveI γ) (play start moveI α)) :=
  ⟨play_zero start moveI,
    fun β α hβα hα => play_pure_chain start moveI hmoveI α hα β hβα,
    fun α => ⟨hmoveI α _, WeakExtends.of_flipEquiv (play_succ_spec start moveI hmoveI α).1⟩,
    fun β α hβα hα => play_moveI_weak start moveI hmoveI β α hβα hα⟩

end Game

end BPHistory
end Erdos1220

#print axioms Erdos1220.BPHistory.flip_flip
#print axioms Erdos1220.BPHistory.FlipEquiv.last_eq
#print axioms Erdos1220.BPHistory.FlipEquiv.liftable
#print axioms Erdos1220.BPHistory.WeakExtends.trans
#print axioms Erdos1220.BPHistory.FlipEquiv.weak_both
#print axioms Erdos1220.BPHistory.WeakExtends.last_extends
#print axioms Erdos1220.BPHistory.WeakExtends.coversBlocks
#print axioms Erdos1220.BPHistory.exists_pure_upper_bound
#print axioms Erdos1220.BPHistory.exists_weak_upper_bound_nat
#print axioms Erdos1220.BPHistory.strategic_closure
